# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Hypoport Bausparkassen Standard Schnittstelle
  description: Standard Schnittstelle zur Berechnung von Bausparangeboten.
  version: "1.0.0"
# the domain of the service
host: api.uber.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /bausparangebote:
    get:
      summary: Berechne Bausparangebote
      description: |
        Der Zugriff auf diese Resource startet die Berechnung von Bausparangeboten.
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/BerechneBausparAnfrage'
          description: Anfrage zur Berechnung der Bausparangebote
          required: true
      tags:
        - Berechnung
      responses:
        200:
          description: An array of products
          schema:
            type: array
            items:
              $ref: '#/definitions/BerechneBausparAntwort'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  BerechneBausparAnfrage:
    properties:
      product_id:
        type: string
        description: Identifier
      bausparsumme:
        type: number
        description: Bausparsumme
      antragsteller:
        type: array
        items:
          $ref: '#/definitions/Anstragsteller'
  Anstragsteller:
    properties:
      uuid:
        type: string
        description: Unique identifier for the activity
  BerechneBausparAntwort:
    properties:
      angebote:
        type: array
        items:
          $ref: '#/definitions/BerechneBausparAngeboteAngebot'
  BerechneBausparAngeboteAngebot:
    properties:
      angebot_id:
        type: string
        description: Identifier
      bausparsumme:
        type: number
        description: Bausparsumme
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
